name: Check Page and Create PR

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
        - info
        - warning
        - debug  
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '0 20 * * *'

jobs:
  check_page_and_create_pr:
    runs-on: ubuntu-latest
    env:
      ACTIONS_ALLOW_UNSECURE_COMMANDS: true

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        pip install requests beautifulsoup4

    - name: Check page for changes
      run: python registration.py
    - name: Create pull request
      if: env.has_changes == 'true'
      uses: peter-evans/create-pull-request@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        title: 'Update based on page changes'
        body: 'The monitored page has changed. This PR updates the repository accordingly.'
        branch: 'page-updates'
        base: 'main'
        commit-message: 'Update repository based on page changes'
